"use client";

import { useState } from "react";

type ToolCall = { tool: string; input: unknown; result: unknown };
type Turn = { question: string; answer?: string; toolCalls?: ToolCall[]; error?: string; loading?: boolean };

const SAMPLE_QUESTIONS = [
  "Which stadium is the highest heat risk in July at 3pm?",
  "Is MetLife Stadium getting hotter over the last 20 years?",
  "How much would 50% shade and 2 misting stations help at Hard Rock Stadium in July at 3pm?",
  "Which stadiums are safest for a June afternoon kickoff?",
];

/** The "Ask" agent -- see app/api/ask/route.ts for the retrieval-then-
 * narrate design. The tool-call trace is shown expanded by default,
 * not hidden behind a "how it works" link -- this audience (sports-
 * science / venue-ops researchers) wants to see exactly which real
 * numbers backed an answer, not just trust prose. */
export default function AskAgent() {
  const [input, setInput] = useState("");
  const [turns, setTurns] = useState<Turn[]>([]);
  const [busy, setBusy] = useState(false);

  async function ask(question: string) {
    if (!question.trim() || busy) return;
    setBusy(true);
    setInput("");
    setTurns((t) => [...t, { question, loading: true }]);
    try {
      const res = await fetch("/api/ask", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ question }),
      });
      const data = await res.json();
      setTurns((t) => {
        const copy = [...t];
        copy[copy.length - 1] = res.ok
          ? { question, answer: data.answer, toolCalls: data.tool_calls }
          : { question, error: data.error ?? "request failed" };
        return copy;
      });
    } catch (e) {
      setTurns((t) => {
        const copy = [...t];
        copy[copy.length - 1] = { question, error: String(e) };
        return copy;
      });
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="flex flex-col h-full font-mono text-sm">
      <div className="border-b border-zinc-800 px-4 py-3">
        <div className="text-zinc-100 font-bold text-xs tracking-wide">ASK &mdash; RESEARCH QUERY AGENT</div>
        <div className="text-zinc-500 text-xs mt-1 max-w-2xl">
          Answers are generated by an LLM (Claude), but it never invents a number: every figure below comes from a
          tool call into this dashboard&apos;s own real data (climatology.json / discovery_trend.json / the scenario
          formula). Expand &quot;data used&quot; on any answer to see the exact tool calls and their
          REAL/MOCK-tagged results.
        </div>
      </div>

      <div className="flex-1 overflow-auto px-4 py-3 flex flex-col gap-4">
        {turns.length === 0 && (
          <div className="flex flex-col gap-2">
            <div className="text-zinc-600 text-xs uppercase tracking-wide">Try asking</div>
            {SAMPLE_QUESTIONS.map((q) => (
              <button
                key={q}
                onClick={() => ask(q)}
                className="text-left px-3 py-2 border border-zinc-800 rounded text-zinc-400 hover:text-zinc-100 hover:border-zinc-600 transition-colors"
              >
                &gt; {q}
              </button>
            ))}
          </div>
        )}

        {turns.map((t, i) => (
          <div key={i} className="flex flex-col gap-1.5">
            <div className="text-zinc-100">
              <span className="text-zinc-600">&gt; </span>
              {t.question}
            </div>
            {t.loading && <div className="text-zinc-600 animate-pulse pl-3">querying real data&hellip;</div>}
            {t.error && <div className="text-red-400 pl-3">error: {t.error}</div>}
            {t.answer && (
              <div className="pl-3 border-l border-zinc-800">
                <div className="text-zinc-200 whitespace-pre-wrap leading-relaxed">{t.answer}</div>
                {t.toolCalls && t.toolCalls.length > 0 && (
                  <details className="mt-2">
                    <summary className="text-zinc-600 text-xs cursor-pointer hover:text-zinc-400">
                      data used ({t.toolCalls.length} lookup{t.toolCalls.length > 1 ? "s" : ""})
                    </summary>
                    <div className="mt-1 flex flex-col gap-2">
                      {t.toolCalls.map((tc, j) => (
                        <div key={j} className="bg-zinc-900 border border-zinc-800 rounded p-2 text-xs overflow-x-auto">
                          <div className="text-zinc-500">
                            {tc.tool}({JSON.stringify(tc.input)})
                          </div>
                          <pre className="text-zinc-400 mt-1">{JSON.stringify(tc.result, null, 2)}</pre>
                        </div>
                      ))}
                    </div>
                  </details>
                )}
              </div>
            )}
          </div>
        ))}
      </div>

      <form
        onSubmit={(e) => {
          e.preventDefault();
          ask(input);
        }}
        className="border-t border-zinc-800 px-4 py-3 flex gap-2"
      >
        <span className="text-zinc-600 self-center">&gt;</span>
        <input
          value={input}
          onChange={(e) => setInput(e.target.value)}
          disabled={busy}
          placeholder="ask a question about heat risk at any of the 11 stadiums..."
          className="flex-1 bg-transparent outline-none text-zinc-100 placeholder:text-zinc-700"
        />
        <button
          type="submit"
          disabled={busy || !input.trim()}
          className="px-3 py-1 rounded border border-zinc-700 text-zinc-400 hover:text-zinc-100 hover:border-zinc-500 disabled:opacity-40"
        >
          ASK
        </button>
      </form>
    </div>
  );
}
